// A simulated transcript for demo purposes since we cannot run yt-dlp/whisper in the browser.
export const DEMO_TRANSCRIPT = `
[00:00:00] Welcome everyone to this deep dive into the future of Artificial Intelligence in software engineering.
[00:00:15] Today we're going to cover three main pillars: The evolution of coding assistants, the shift from copilot to autopilot, and the ethical implications of AI-generated code.
[00:01:00] Let's start with history. In the early 2020s, we saw the rise of LLMs like GPT-3. These were glorified autocomplete engines. They could finish your line, but they couldn't architect a system.
[00:02:30] Fast forward to today. We are seeing "Agentic Workflows". This means the AI doesn't just write code; it plans, executes, tests, and fixes its own mistakes.
[00:03:45] For example, look at the new Devin or Gemini Code Assist features. You give it a high-level goal, like "Build a React app for a todo list", and it scaffolds the files, installs dependencies, and writes the logic.
[00:05:00] However, this brings us to the second pillar: The "Autopilot" problem. If the AI does everything, do junior developers still learn? We risk creating a generation of architects who can't lay bricks.
[00:06:20] It's crucial that we treat AI as a force multiplier, not a replacement for fundamental knowledge. You need to know when the AI is hallucinating.
[00:08:15] Finally, ethics. Who owns the code generated by an AI trained on open source? The legal battles are just beginning.
[00:09:00] To summarize, the future is bright but requires vigilance. We must evolve from code writers to system prompt engineers and reviewers.
[00:10:00] Thank you for listening. Let's open it up for Q&A.
`;

export const MOCK_LOGS = [
  "Connecting to YouTube service...",
  "Extracting audio track (128kbps)...",
  "Audio downloaded successfully (4.2MB).",
  "Initializing Whisper (Small) model...",
  "Transcribing segment 1/5...",
  "Transcribing segment 2/5...",
  "Transcribing segment 3/5...",
  "Transcribing segment 4/5...",
  "Transcribing segment 5/5...",
  "Transcription complete. Preparing text for analysis..."
];